src/Entity/Character.php
<?php

namespace App\Entity;

use App\Repository\CharacterRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CharacterRepository::class)
 * @ORM\Table(name="`character`")
 */
class Character
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $health;

    /**
     * @ORM\Column(type="integer")
     */
    private $attack;

    /**
     * @ORM\Column(type="integer")
     */
    private $total_exp;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="avatar")
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Equipement::class, mappedBy="characters")
     */
    private $equipements;

    public function __construct()
    {
        $this->equipements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHealth(): ?int
    {
        return $this->health;
    }

    public function setHealth(int $health): self
    {
        $this->health = $health;

        return $this;
    }

    public function getAttack(): ?int
    {
        return $this->attack;
    }

    public function setAttack(int $attack): self
    {
        $this->attack = $attack;

        return $this;
    }

    public function getTotalExp(): ?int
    {
        return $this->total_exp;
    }

    public function setTotalExp(int $total_exp): self
    {
        $this->total_exp = $total_exp;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Equipement[]
     */
    public function getEquipements(): Collection
    {
        return $this->equipements;
    }

    public function addEquipement(Equipement $equipement): self
    {
        if (!$this->equipements->contains($equipement)) {
            $this->equipements[] = $equipement;
            $equipement->addCharacter($this);
        }

        return $this;
    }

    public function removeEquipement(Equipement $equipement): self
    {
        if ($this->equipements->contains($equipement)) {
            $this->equipements->removeElement($equipement);
            $equipement->removeCharacter($this);
        }

        return $this;
    }
}

src/Controller/CharacterController.php
<?php

namespace App\Controller;

use App\Entity\Character;
use App\Form\CharacterType;
use App\Repository\CharacterRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/character")
 * @IsGranted("ROLE_USER")
 */
class CharacterController extends AbstractController
{
    /**
     * @Route("/", name="character_index", methods={"GET"})
     */
    /* 
    public function index(CharacterRepository $characterRepository): Response
    {
        return $this->render('character/index.html.twig', [
            'characters' => $characterRepository->findAll(),
        ]);
    } 
    */

    /**
     * @Route("/new", name="character_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $character = new Character();
        $user = $this->getUser();
        if ($user->getAvatar() !== NULL)
        {
            return $this->redirectToRoute('character_show', ['id' => $user->getId()]);
        }

            $entityManager = $this->getDoctrine()->getManager();
            $character->setUser($user);
            $character->setTotalExp(0);
            $character->setHealth(50);
            $character->setAttack(10);
            $entityManager->persist($character);
            $entityManager->flush();

            return $this->redirectToRoute('character_show', ['id' => $user->getId()]);
    }

    /**
     * @Route("/{id}", name="character_show", methods={"GET"})
     */
    public function show(Character $character): Response
    {
        return $this->render('character/show.html.twig', [
            'character' => $character,
        ]);
    }
}

templates/character/_delete_form.html.twig
<form method="post" action="{{ path('character_delete', {'id': character.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ character.id) }}">
    <button class="btn">Delete</button>
</form>

templates/character/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/character/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Character{% endblock %}

{% block body %}
    <h1>Edit Character</h1>

    {{ include('character/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('character_index') }}">back to list</a>

    {{ include('character/_delete_form.html.twig') }}
{% endblock %}

templates/character/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Character index{% endblock %}

{% block body %}
    <h1>Character index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Hair_id</th>
                <th>Chest_id</th>
                <th>Legs_id</th>
                <th>Health</th>
                <th>Total_exp</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for character in characters %}
            <tr>
                <td>{{ character.id }}</td>
                <td>{{ character.HairId }}</td>
                <td>{{ character.ChestId }}</td>
                <td>{{ character.LegsId }}</td>
                <td>{{ character.health }}</td>
                <td>{{ character.totalExp }}</td>
                <td>
                    <a href="{{ path('character_show', {'id': character.id}) }}">show</a>
                    <a href="{{ path('character_edit', {'id': character.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('character_new') }}">Create new</a>
{% endblock %}

templates/character/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Character{% endblock %}

{% block body %}
    <h1>Create new Character</h1>

    {{ include('character/_form.html.twig') }}

    <a href="{{ path('character_show', {'id':user.id}) }}">back to list</a>
{% endblock %}

templates/character/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Character{% endblock %}

{% block body %}
    <h1>Character</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ character.id }}</td>
            </tr>
            <tr>
                <th>Health</th>
                <td>{{ character.health }}</td>
            </tr>
            <tr>
                <th>Attack</th>
                <td>{{ character.attack }}</td>
            </tr>
            <tr>
                <th>Total_exp</th>
                <td>{{ character.totalExp }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}